# Server Name
server-name: "§c[§eKillBoarder§c]§e"
players:
leaderboard:
# Set true if you want killed mobs to count as 1 points.
isMobKill: true
# {player} : Player Name
# {number} : Number kill
# {place} : Player Place
text-format: "{place}. {player} : {number}Kills"
max-place: 10